"""first

Revision ID: dac8f05489e3
Revises: 
Create Date: 2021-06-22 21:52:06.905110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac8f05489e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests_train',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_station', sa.String(), nullable=True),
    sa.Column('finish_station', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests_train')
    # ### end Alembic commands ###
